### ISSUE TITLE
The link is invalid

### ISSUE THREAD

**Issue by hcunyu** [Uo1428/AnotherJourney#4]
<img width="437" alt="屏幕截图 2024-04-13 192819" src="https://github.com/Uo1428/AnotherJourney/assets/104993330/4a881ff5-56c8-4fab-9465-8e60e4d52f61">
and
<img width="696" alt="屏幕截图 2024-04-13 192918" src="https://github.com/Uo1428/AnotherJourney/assets/104993330/66753da2-3600-454e-98a6-50caef2df664">

**Comment by Uo1428** [comment]
https://discord.uoaio.xyz
